services:
  postgres:
    image: postgres:latest
    container_name: demo-postgres

    environment:
      POSTGRES_DB: worknote
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    ports:
      - "55916:5432"